os:
  - linux
  - osx
language: perl6
perl6:
  - latest
  - '2017.05'
  - '2017.04'
install:
  - rakudobrew build-zef
  - zef --debug --depsonly install .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
