os:
  - linux
  - osx
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-zef
  - panda --notests installdeps .
script:
  - zef --debug --depsonly install .
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
